### ISSUE TITLE
Example fails with missing inputs: install

### ISSUE THREAD

**Issue by Samze** [danielsiwiec/concourse-demo#1]
This example appears to be output of date. Tasks can no longer be used in proceeding inputs into other tasks.

Running this example results in `missing inputs: install`

**Comment by danielsiwiec** [comment]
@Samze thanks for filling this. I will look into this shortly

**Comment by danielsiwiec** [comment]
@Samze I applied some fixes in the demo for Concourse 1.2.0.
Also, the original blog post is now refreshed for the recent version and available [here](http://danoncoding.com/programming/2016/05/05/setting-up-a-simple-pipeline-with-concourse-ci-redux/)

Let me know if you still have any issues

**Comment by Samze** [comment]
Great @danielsiwiec! Thank you
